---
- name: include variable overrides
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "vars/{{ ansible_distribution }}.yml"
        - "vars/{{ ansible_os_family }}.yml"
      skip: true

- name: install packages
  package:
    name: "{{ item }}"
    state: "{{ rabbitmq_packages_state }}"
  with_items: "{{ rabbitmq_packages | default(rabbitmq_packages_default) }}"
  notify:
    - remove default vhost
    - remove guest user

- name: manage services
  service:
    name: "{{ item }}"
    state: "{{ rabbitmq_service_status }}"
    enabled: "{{ rabbitmq_service_enabled }}"
  with_items: "{{ rabbitmq_service_names | default(rabbitmq_service_names_default) }}"

- name: enable rabbitmq management
  changed_when: false
  command: rabbitmq-plugins enable rabbitmq_management

- name: query vhosts
  changed_when: false
  command: "rabbitmqctl list_vhosts"
  register: rabbitmq_vhosts

- name: create vhost
  command: "rabbitmqctl add_vhost {{ rabbitmq_vhost }}"
  when:
    - rabbitmq_vhost != ''
    - rabbitmq_vhost not in rabbitmq_vhosts.stdout_lines

- name: query users
  changed_when: false
  command: rabbitmqctl list_users
  register: rabbitmq_users

- name: create user
  command: "rabbitmqctl add_user {{ rabbitmq_user_name }} {{ rabbitmq_user_pass}}"
  when:
    - rabbitmq_user_name != ''
    - rabbitmq_user_name not in rabbitmq_users.stdout_lines

- name: set user pass
  command: "rabbitmqctl change_password {{ rabbitmq_user_name }} {{ rabbitmq_user_pass}}"
  when:
    - rabbitmq_user_name != ''
  changed_when: false

- name: configure user
  command: "rabbitmqctl set_permissions -p {{ rabbitmq_vhost }} {{ rabbitmq_user_name }} '{{ rabbitmq_user_perm_conf }}' '{{ rabbitmq_user_perm_write }}' '{{ rabbitmq_user_perm_read }}'"
  tags:
    - skip_ansible_lint
  when:
    - rabbitmq_vhost != ''
    - rabbitmq_user_name != ''
  changed_when: false

- name: set user tags
  command: "rabbitmqctl set_user_tags {{ rabbitmq_user_name }} {{ rabbitmq_user_tags | join(' ') }}"
  tags:
    - skip_ansible_lint
  when:
    - rabbitmq_user_name != ''
    - rabbitmq_user_tags != []
  changed_when: false
